import type { Destination, Property, Room, Experience, Offer } from './types';

// Local destination photography lives in /public/destinations/.
// BASE_URL is '/' in dev and '/V-LORA-HOTELS-RESORTS/' on GitHub Pages.
const IMG = (name: string) => `${import.meta.env.BASE_URL}destinations/${name}`;

// ─── Destinations ────────────────────────────────────────────────────────────
// All priceFromUSD values are in USD; runtime formatting handled by useCurrency

export const destinations: Destination[] = [
  // ASIA
  {
    id: 'maldives',
    name: 'Maldives',
    country: 'Indian Ocean',
    region: 'asia',
    filterTypes: ['island', 'beach', 'wellness'],
    type: 'island',
    propertyName: 'VÉLORA Noonu',
    priceFromUSD: 680,
    lat: 5.73,
    lng: 73.52,
    coords: '5.7300° N, 73.5200° E',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Private overwater pavilions at sunrise',
    description: 'A thousand coral islands scattered across the equatorial ocean. The Maldives is stillness in its purest form — glass-calm lagoons, reefs alive with colour, and the kind of silence that lets you breathe differently.',
    climate: 'Tropical, year-round warmth',
    bestTime: 'November – April',
  },
  {
    id: 'srilanka',
    name: 'Sri Lanka',
    country: 'South Asia',
    region: 'asia',
    filterTypes: ['wellness', 'beach', 'cultural'],
    type: 'wellness',
    propertyName: 'VÉLORA Tangalle',
    priceFromUSD: 420,
    lat: 7.87,
    lng: 80.77,
    coords: '7.8731° N, 80.7718° E',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Ayurvedic ceremonies in jungle retreats',
    description: 'An island of extraordinary contrasts — ancient temples in dense jungle, colonial tea estates ascending misty highlands, and a coastline that curves between fishing villages and whale-watching waters.',
    climate: 'Tropical, monsoon seasons vary by region',
    bestTime: 'December – March (West), May – September (East)',
  },
  {
    id: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'asia',
    filterTypes: ['city', 'cultural', 'wellness'],
    type: 'cultural',
    propertyName: 'VÉLORA Higashiyama',
    priceFromUSD: 640,
    lat: 35.01,
    lng: 135.77,
    coords: '35.0116° N, 135.7681° E',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Kaiseki dinners in centuries-old machiya',
    description: 'Ancient Japan, preserved. Kyoto moves at a considered pace — tea ceremonies, moss gardens, the soft creak of temple wood. Our property is within cycling distance of Fushimi Inari, yet perfectly removed from it.',
    climate: 'Temperate, four distinct seasons',
    bestTime: 'March – May, October – November',
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'asia',
    filterTypes: ['wellness', 'cultural', 'mountain'],
    type: 'wellness',
    propertyName: 'VÉLORA Ubud',
    priceFromUSD: 480,
    lat: -8.34,
    lng: 115.09,
    coords: '8.3405° S, 115.0919° E',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Jungle-edge infinity pools at altitude',
    description: 'Ubud ascends through rice terraces and sacred forests to a plateau where the sky opens and spiritual life is unperformed. Our property sits among the mist, with views of Agung at dawn.',
    climate: 'Tropical, two seasons',
    bestTime: 'May – September',
  },
  {
    id: 'thailand',
    name: 'Koh Samui',
    country: 'Thailand',
    region: 'asia',
    filterTypes: ['beach', 'island', 'wellness'],
    type: 'beach',
    propertyName: 'VÉLORA Koh Samui',
    priceFromUSD: 540,
    lat: 9.54,
    lng: 100.06,
    coords: '9.5400° N, 100.0600° E',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Beachfront villas with private sea access',
    description: "Koh Samui's northern coast faces a gulf that barely moves in the dry season — warm, shallow, and the colour of green tourmaline. Our villas step directly onto their own stretch of sand.",
    climate: 'Tropical, best season November – April',
    bestTime: 'November – April',
  },

  // EUROPE
  {
    id: 'amalfi',
    name: 'Amalfi Coast',
    country: 'Italy',
    region: 'europe',
    filterTypes: ['beach', 'cultural', 'wellness'],
    type: 'cultural',
    propertyName: 'VÉLORA Ravello',
    priceFromUSD: 950,
    lat: 40.63,
    lng: 14.60,
    coords: '40.6340° N, 14.6027° E',
    image: 'https://images.unsplash.com/photo-1561501878-aabd62634533?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Cliff-top dining above the Tyrrhenian',
    description: 'Where limestone cliffs meet jade waters. The Amalfi Coast offers a landscape so theatrical it feels imagined — lemon groves terracing down to ancient fishing villages, each overlooking a sea that changes colour by the hour.',
    climate: 'Mediterranean, warm and dry summers',
    bestTime: 'May – June, September – October',
  },
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    region: 'europe',
    filterTypes: ['island', 'beach', 'cultural'],
    type: 'island',
    propertyName: 'VÉLORA Oia',
    priceFromUSD: 920,
    lat: 36.39,
    lng: 25.46,
    coords: '36.3932° N, 25.4615° E',
    image: 'https://images.unsplash.com/photo-1586096717965-60d27e60dd3f?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Caldera-edge infinity pools at sunset',
    description: 'Whitewashed geometry against a volcanic sea. Santorini\'s beauty is geometric and elemental — curved walls, cobalt domes, and a caldera that holds the last light of every evening longer than anywhere else on earth.',
    climate: 'Mediterranean, dry and warm',
    bestTime: 'April – June, September – October',
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'europe',
    filterTypes: ['city', 'cultural'],
    type: 'city',
    propertyName: 'VÉLORA Saint-Germain',
    priceFromUSD: 1100,
    lat: 48.85,
    lng: 2.35,
    coords: '48.8566° N, 2.3522° E',
    image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Private hôtel particulier on the Left Bank',
    description: 'In the 7th arrondissement, behind an unlisted entrance, a restored hôtel particulier of seven suites. Paris at its most interior — art, food, long afternoons in the city\'s most composed quarter.',
    climate: 'Temperate oceanic',
    bestTime: 'April – June, September – October',
  },
  {
    id: 'dolomites',
    name: 'Dolomites',
    country: 'Italy',
    region: 'europe',
    filterTypes: ['mountain', 'wellness'],
    type: 'mountain',
    propertyName: 'VÉLORA Cortina',
    priceFromUSD: 780,
    lat: 46.54,
    lng: 12.14,
    coords: '46.5404° N, 12.1357° E',
    image: 'https://www.thetrainline.com/cms/media/7917/italy-dolomites-hotel-hubertus.jpg',
    stayCount: 1,
    signature: 'Alpine chalet spa above the treeline',
    description: 'The Dolomites are among the world\'s most improbable landscapes — rose-pink limestone towers above pine forests, meadows quilted with wildflowers, and winter light that arrives low and golden all day.',
    climate: 'Alpine, cool summers, snowy winters',
    bestTime: 'June – September, December – March',
  },

  // MIDDLE EAST
  {
    id: 'oman',
    name: 'Muscat',
    country: 'Oman',
    region: 'middle-east',
    filterTypes: ['beach', 'cultural', 'wellness'],
    type: 'cultural',
    propertyName: 'VÉLORA Muscat',
    priceFromUSD: 580,
    lat: 23.61,
    lng: 58.59,
    coords: '23.6100° N, 58.5900° E',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Desert wadi excursions at first light',
    description: 'Oman is the Arab world without performance. A coastline of fjords and sand dunes, a culture of quiet generosity, and a capital that builds for permanence. Our property faces the Gulf of Oman with desert behind.',
    climate: 'Arid, mild in winter months',
    bestTime: 'October – April',
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    region: 'middle-east',
    filterTypes: ['city', 'beach'],
    type: 'city',
    propertyName: 'VÉLORA Palm',
    priceFromUSD: 950,
    lat: 25.20,
    lng: 55.27,
    coords: '25.2048° N, 55.2708° E',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Private beach access on the Palm',
    description: 'On the Palm\'s frond, removed from the skyline spectacle, a low-rise residence of nineteen rooms. Direct beach access, a sea-view spa and a kitchen sourcing from the Arabian Gulf daily.',
    climate: 'Hot arid desert, mild winters',
    bestTime: 'November – March',
  },

  // AFRICA & INDIAN OCEAN
  {
    id: 'seychelles',
    name: 'Seychelles',
    country: 'Indian Ocean',
    region: 'africa',
    filterTypes: ['island', 'beach', 'wellness'],
    type: 'island',
    propertyName: 'VÉLORA Praslin',
    priceFromUSD: 720,
    lat: -4.32,
    lng: 55.73,
    coords: '4.3200° S, 55.7300° E',
    image: 'https://d3hk78fplavsbl.cloudfront.net/assets/common-prod/hotel/205/423744/423744-1-hotel_carousel_large.jpg?version=9',
    stayCount: 1,
    signature: 'Bouldered coves and private coral gardens',
    description: 'On Praslin, granite boulders worn smooth by millennia define a coastline unlike anywhere else. The Vallée de Mai is minutes away; our villas face a lagoon where the water is the same warm green as the palms.',
    climate: 'Tropical, warm year-round',
    bestTime: 'April – May, October – November',
  },
  {
    id: 'mauritius',
    name: 'Mauritius',
    country: 'Indian Ocean',
    region: 'africa',
    filterTypes: ['island', 'beach', 'wellness'],
    type: 'island',
    propertyName: 'VÉLORA Beau Rivage',
    priceFromUSD: 660,
    lat: -20.16,
    lng: 57.55,
    coords: '20.1600° S, 57.5500° E',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Lagoon-side villas at sunset',
    description: 'Mauritius is more layered than most island destinations — Creole culture, volcanic peaks inland, and a reef-protected lagoon on the western coast where the water calms and deepens to indigo. Our property faces that lagoon.',
    climate: 'Tropical, most pleasant May – November',
    bestTime: 'May – November',
  },

  // AMERICAS
  {
    id: 'costarica',
    name: 'Costa Rica',
    country: 'Central America',
    region: 'americas',
    filterTypes: ['wellness', 'mountain', 'beach'],
    type: 'wellness',
    propertyName: 'VÉLORA Nicoya',
    priceFromUSD: 580,
    lat: 9.75,
    lng: -84.22,
    coords: '9.7489° N, 84.2195° W',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Jungle canopy retreats in the blue zone',
    description: 'The Nicoya Peninsula is one of the world\'s five Blue Zones — a place where people live measurably longer. Our retreat is set in old-growth forest above a Pacific beach, designed entirely around stillness and renewal.',
    climate: 'Tropical, dry season December – April',
    bestTime: 'December – April',
  },

  // Keep Marrakech
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    region: 'africa',
    filterTypes: ['city', 'cultural', 'wellness'],
    type: 'cultural',
    propertyName: 'VÉLORA Medina',
    priceFromUSD: 640,
    lat: 31.63,
    lng: -7.98,
    coords: '31.6295° N, 7.9811° W',
    image: 'https://images.unsplash.com/photo-1561501878-aabd62634533?w=800&h=600&fit=crop&auto=format',
    stayCount: 1,
    signature: 'Candlelit riad courtyards at dusk',
    description: "The city that seduces all five senses at once. Inside VÉLORA's restored riads, the medina's intensity becomes something else entirely — jasmine-cooled courtyards, hammam rituals, and tables set beneath the stars.",
    climate: 'Semi-arid, hot and dry',
    bestTime: 'March – May, October – November',
  },
];

// ─── Rooms (shared base, adapted per property) ───────────────────────────────
// All prices in USD

const makeRooms = (prefix: string, multiplier: number = 1): Room[] => [
  {
    id: `${prefix}-grand`,
    name: 'Grand Terrace Suite',
    category: 'Suite',
    size: 85,
    guests: 2,
    view: 'Sea',
    bed: 'King',
    pricePerNight: Math.round(1240 * multiplier),
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&h=600&fit=crop&auto=format',
    description: 'An elevated sanctuary with a wraparound terrace suspended above the water. Morning coffee with the sea ahead, afternoon golden hour from your private loungers.',
    amenities: ['Private terrace', 'Plunge pool', 'Marble bathroom', 'Butler service', 'Evening turndown', 'Minibar', 'Sea view bath'],
    hasPool: true,
    hasButler: true,
    hasBreakfast: true,
    matchScore: 96,
  },
  {
    id: `${prefix}-pavilion`,
    name: 'Sea Pavilion Room',
    category: 'Deluxe Room',
    size: 52,
    guests: 2,
    view: 'Sea',
    bed: 'King',
    pricePerNight: Math.round(780 * multiplier),
    image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=900&h=600&fit=crop&auto=format',
    description: 'Refined calm with direct views. Floor-to-ceiling glass opens to a juliet balcony where the light comes in warm and unhurried every morning.',
    amenities: ['Juliet balcony', 'Rain shower', 'Nespresso station', 'Marble bath', 'Evening turndown'],
    hasPool: false,
    hasButler: false,
    hasBreakfast: false,
    matchScore: 82,
  },
  {
    id: `${prefix}-villa`,
    name: 'Private Villa',
    category: 'Villa',
    size: 180,
    guests: 4,
    view: 'Panoramic',
    bed: 'King + Twin',
    pricePerNight: Math.round(2800 * multiplier),
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=900&h=600&fit=crop&auto=format',
    description: 'A private residence with your own pool, outdoor dining area, and a living room that frames the entire landscape. For those who want the destination entirely to themselves.',
    amenities: ['Private pool', 'Outdoor dining terrace', 'Butler 24h', 'Private kitchen', 'Two bedrooms', 'Cellar access', 'Concierge'],
    hasPool: true,
    hasButler: true,
    hasBreakfast: true,
    matchScore: 91,
  },
];

// ─── Properties ──────────────────────────────────────────────────────────────

export const properties: Property[] = destinations.map(d => ({
  id: `velora-${d.id}`,
  name: d.propertyName,
  destination: d.name,
  destinationId: d.id,
  image: d.image,
  rating: 9.6 + Math.random() * 0.4,
  priceFrom: d.priceFromUSD,
  signature: d.signature,
  description: d.description.slice(0, 120) + '…',
  rooms: makeRooms(d.id, d.priceFromUSD / 780),
}));

// ─── Experiences ─────────────────────────────────────────────────────────────

export const experiences: Experience[] = [
  {
    id: 'sunset-dinner',
    name: 'Private Sunset Dinner',
    category: 'dine',
    duration: '3 hours',
    price: 380,
    location: 'Cliff Terrace',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop&auto=format',
    description: 'A table for two on the private terrace. Your chef prepares a menu written around the season. The sea below, the sky ahead.',
  },
  {
    id: 'ocean-ritual',
    name: 'Ocean Ritual Spa',
    category: 'rest',
    duration: '2.5 hours',
    price: 280,
    location: 'VÉLORA Spa',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop&auto=format',
    description: 'Sea minerals, warm stone and the rhythm of tides. A full-body treatment drawing on coastal traditions, ending in a salt pool overlooking the water.',
  },
  {
    id: 'morning-yoga',
    name: 'Sunrise Yoga & Meditation',
    category: 'move',
    duration: '75 minutes',
    price: 95,
    location: 'Garden Pavilion',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop&auto=format',
    description: 'Begin the day before the world does. A private session with our resident teacher, positioned to greet the first light across the water.',
  },
  {
    id: 'island-sailing',
    name: 'Private Island Sail',
    category: 'explore',
    duration: 'Full day',
    price: 1200,
    location: 'Marina',
    image: 'https://images.unsplash.com/photo-1559521778-84816b3d2f3d?w=800&h=600&fit=crop&auto=format',
    description: 'A crewed schooner, a cooler of local wine, and a coastline with no itinerary. Anchor in hidden coves, swim in clear water, and return at dusk.',
  },
  {
    id: 'chefs-table',
    name: "Chef's Table",
    category: 'dine',
    duration: '4 hours',
    price: 520,
    location: 'Kitchen Studio',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop&auto=format',
    description: 'Inside the kitchen, beside the chef. An eight-course journey through local produce, explained course by course, with wines matched from our cellar.',
  },
  {
    id: 'cultural-walk',
    name: 'Cultural Discovery Walk',
    category: 'explore',
    duration: '3 hours',
    price: 160,
    location: 'Village & Beyond',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&h=600&fit=crop&auto=format',
    description: 'Walk with someone who grew up here. Artisan studios, family-run bakeries, hidden viewpoints that no map remembers. Breakfast included.',
  },
  {
    id: 'villa-breakfast',
    name: 'Private Villa Breakfast',
    category: 'dine',
    duration: '90 minutes',
    price: 120,
    location: 'Your Villa',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&h=600&fit=crop&auto=format',
    description: 'Everything from the morning market, arranged beautifully and served in your garden or on your terrace. Time belongs entirely to you.',
  },
  {
    id: 'wellness-consult',
    name: 'Wellness Consultation',
    category: 'rest',
    duration: '60 minutes',
    price: 180,
    location: 'VÉLORA Spa',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=600&fit=crop&auto=format',
    description: 'A conversation with our resident wellness practitioner. Understand your body, set intentions for the stay, and leave with a personal ritual map.',
  },
];

// ─── Offers ──────────────────────────────────────────────────────────────────

export const offers: Offer[] = [
  {
    id: 'long-stay',
    title: 'The Long Stay',
    subtitle: 'Seven nights. Unbounded.',
    description: "Time is the greatest luxury. Stay seven nights and we'll add what matters most — daily breakfast, a signature spa ritual, and a private dining evening at no additional cost.",
    inclusions: ['Daily breakfast for two', 'One Ocean Ritual Spa per person', 'Private dinner on cliff terrace', 'Early check-in, late checkout', 'Complimentary airport transfer'],
    terms: 'Minimum 7 nights. Subject to availability. Non-refundable.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&h=600&fit=crop&auto=format',
    nights: 7,
    savings: '18%',
  },
  {
    id: 'romantic',
    title: 'Romantic Journey',
    subtitle: 'For two who want to disappear.',
    description: "A curated sequence of moments designed for two. Champagne on arrival, a sunset dinner, a couples' spa ritual, and a morning sail that belongs only to you.",
    inclusions: ['Champagne & fruit on arrival', 'Sunset cliff dinner', 'Couples Ocean Ritual', 'Private morning sail', 'Floral arrangement in room', 'Farewell gift'],
    terms: 'Minimum 3 nights. Advance booking required.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&h=600&fit=crop&auto=format',
    nights: 3,
    savings: '12%',
  },
  {
    id: 'wellness',
    title: 'Wellness Reset',
    subtitle: 'Five days to return to yourself.',
    description: 'Arrive with tension. Leave with clarity. A five-night programme built around sleep, movement, nourishment and stillness — structured but never rigid.',
    inclusions: ['Daily wellness consultation', 'Morning yoga (5 sessions)', 'Three spa treatments', 'Nutritional meal plan', 'Meditation sessions', 'Wellness journal'],
    terms: 'Minimum 5 nights. Health questionnaire required.',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=900&h=600&fit=crop&auto=format',
    nights: 5,
    savings: '15%',
  },
  {
    id: 'family',
    title: 'Family Journey',
    subtitle: 'Adventures for all ages.',
    description: 'The full VÉLORA experience, designed for families. Space, freedom and activities that mean something — from morning cookery for children to evening cinema under the stars.',
    inclusions: ['Connecting rooms or villa', "Children's welcome basket", 'Daily family activity', 'Childcare (3 evenings)', 'Family boat day', 'Children dine free'],
    terms: 'Minimum 4 nights. Children 12 and under.',
    image: 'https://images.unsplash.com/photo-1586096717965-60d27e60dd3f?w=900&h=600&fit=crop&auto=format',
    nights: 4,
    savings: '10%',
  },
  {
    id: 'seasonal',
    title: 'Seasonal Escape',
    subtitle: 'September. The perfect month.',
    description: 'September is when the light softens, the crowds return home, and the coast reclaims itself. Our September offer includes preferential rates across all room categories.',
    inclusions: ['Preferential September rate', 'Daily breakfast', 'One signature experience', 'Welcome amenity'],
    terms: 'Valid September 1–30. Flexible cancellation.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=900&h=600&fit=crop&auto=format',
    nights: 2,
    savings: '20%',
  },
];

// Re-export Room type helper used in Stays
export type { Room };
